apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-booking-api
  namespace: app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel-booking-api
  template:
    metadata:
      labels:
        app: hotel-booking-api
    spec:
      containers:
      - name: hotel-booking-api
        image: shreyojit/hotel-booking-api:latest
        ports:
        - containerPort: 7000
